use serde_yaml::{Mapping, Value};
use std::env;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

const BUILD_NUMBER_RS: &str = "build_number.rs";

fn main() {
    export_messages();
    export_build_number_and_edition();
}

// build_number.rsのbuild_numberとeditionを生成・更新する
fn export_build_number_and_edition() {
    let build_number = parse_build_number_from_build_number_rs();
    let edition = parse_edition_from_cargo_toml().unwrap_or_else(|| "unknown".to_string());
    // build_number.rsを上書き
    let mut f = fs::File::create(BUILD_NUMBER_RS).unwrap();
    writeln!(f, "// This file is automatically generated by build.rs").unwrap();
    writeln!(f, "// Do not edit manually.").unwrap();
    writeln!(f, "pub const BUILD_NUMBER: &str = \"{}\";", build_number).unwrap();
    writeln!(f, "pub const EDITION: &str = \"{}\";", edition).unwrap();
    println!("cargo:rerun-if-changed={}", BUILD_NUMBER_RS);
}

fn parse_build_number_from_build_number_rs() -> u64 {
    // 環境変数RESET_BUILD_NUMBERが設定されていればそれを使う
    if let Ok(val) = env::var("RESET_BUILD_NUMBER") {
        if let Ok(num) = val.parse::<u64>() {
            return num;
        }
    }
    // 既存のbuild_number.rsから番号を取得
    if let Ok(mut f) = fs::File::open(BUILD_NUMBER_RS) {
        let mut content = String::new();
        if f.read_to_string(&mut content).is_ok() {
            if let Some(line) = content.lines().find(|l| l.contains("BUILD_NUMBER")) {
                if let Some(num_str) = line.split('"').nth(1) {
                    if let Ok(num) = num_str.parse::<u64>() {
                        return num + 1;
                    }
                }
            }
        }
    }
    return 0;
}

/// Cargo.tomlからeditionをパースして返す
fn parse_edition_from_cargo_toml() -> Option<String> {
    let content = std::fs::read_to_string("Cargo.toml").ok()?;
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("edition") {
            let parts: Vec<&str> = line.split('=').collect();
            if parts.len() == 2 {
                return Some(parts[1].trim().trim_matches('"').to_string());
            }
        }
    }
    None
}

/// messagesディレクトリ以下のすべてのYAMLファイルを読み込み、1つのネストされたYAML構造にマージして
/// Rustの静的変数として埋め込む。
fn export_messages() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("messages_embedded.rs");

    let mut root = Mapping::new();

    for entry in glob::glob("messages/**/*.yaml").unwrap() {
        let path = entry.unwrap();
        let value: Value = serde_yaml::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
        let keys = path_to_keys(&path);
        insert_nested(&mut root, &keys, value);
    }

    let merged = Value::Mapping(root);
    let yaml_str = serde_yaml::to_string(&merged).unwrap();

    let mut f = File::create(&dest_path).unwrap();
    // Rustの静的変数として埋め込む
    writeln!(f, "pub const MESSAGES_YAML: &str = r#\"{}\"#;", yaml_str).unwrap();

    println!("cargo:rerun-if-changed=messages/");
}

fn path_to_keys(path: &PathBuf) -> Vec<String> {
    let mut keys = Vec::new();
    let mut iter = path.iter().skip_while(|c| *c != "messages");
    iter.next(); // skip "messages"
    for comp in iter {
        let s = comp.to_string_lossy();
        if s.ends_with(".yaml") {
            keys.push(s.trim_end_matches(".yaml").to_string());
        } else {
            keys.push(s.to_string());
        }
    }
    keys
}

fn insert_nested(map: &mut Mapping, keys: &[String], value: Value) {
    if keys.is_empty() {
        return;
    }
    if keys.len() == 1 {
        map.insert(Value::String(keys[0].clone()), value);
    } else {
        let entry = map.entry(Value::String(keys[0].clone())).or_insert_with(|| Value::Mapping(Mapping::new()));
        if let Value::Mapping(submap) = entry {
            insert_nested(submap, &keys[1..], value);
        }
    }
}
